import type { AppProps } from 'next/app'
import 'bootstrap/dist/css/bootstrap.min.css';
import Head from 'next/head';
import Navbar from '../component/Navbar';
export default function App({ Component, pageProps }: AppProps) {
  return <>
    <Head>
      <title>Pranto Chakraborty</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Navbar />
    <Component {...pageProps} />
  </>
}
